### PR TITLE
added LWT to f_connect for mqtt and changed minor_version to 25 to al…

### PR DESCRIPTION
**Pull request by hi-flyer**
added LWT capability to detect unexpected disconnect by control applications on mqtt
added new minor version upgrade to detect LWT support of unexpected loss of connection for mqtt

### CODE REVIEW

**Comment by hi-flyer** [comment]
Should have added, I did test this on my device and it does work.

**Comment by hi-flyer** [comment]
Have received comment to upgrade my version of LWT. Will test and add a new commit if successful.

**Comment by hi-flyer** [comment]
Have made the enhancement and it preforms as expected on my device.

**Review by hi-flyer — COMMENTED** [review]
this change in longer term testing has the garadget showing Offline on some unknown trigger by I suspect the broker even though the garadget is still working. Will investigate further to detect the issue. this needs to be fixed before approval.

**Comment by yeti7** [comment]
@hi-flyer,
Thank you for your contribution!

**Pull request merged**
