### PR TITLE
Update MQTT code to support reboot and bump minor version to 26

### PR DESCRIPTION
**Pull request by Krazy998**
Minor additional feature to allow reboot of the device via MQTT and bump minor version to 26.

### CODE REVIEW

**Comment by Krazy998** [comment]
@hi-flyer let me know if this looks good - based on your feedback. Minor code update to mqtt to allow rebooting and bumped version up.

**Comment by hi-flyer** [comment]
Yes, looks ok to me. It appear that it should only add a new capability and not cause conflict with anything else on the mqtt. I only used the device in mqtt local mode so I really do not know about the other mode of operation but I think this change should not be a problem for it.

**Review by yeti7 — APPROVED** [review]

**Comment by Krazy998** [comment]
Awesome thanks @yeti7 - is there anything else we need to get this merged? Seems to still be open. Also whats the approach to pushing this to the device?

**Comment by yeti7** [comment]
Re. device update: you can compile it locally and upload via USB.

**Pull request merged**
